### ISSUE TITLE
iPad Air 2 iOS 15.7.7 partial fakefs stuck

### ISSUE THREAD

**Issue by haniag** [palera1n/jbinit#11]
When I run ./palera1n -Bf on iPad Air 2 iOS 15.7.7 with a fresh restore and no code entered, the process gets stuck on creating fakefs:

https://imgur.com/gO9zCmw

**Comment by azaz0322** [comment]
This is not the place to open an issue for palera1n.
Join the Discord server to get support instead.

**Comment by haniag** [comment]
Sounds good.
