### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by ssdrive-flaktra** [palera1n/jbinit#13]
When trying to run the latest actions build of plooshinit (downloaded from cdn.nickchan.lol) using palera1n (built from main), it gets to the "palera1n" splash screen, but crashes around 5 seconds after displaying it. Attached is a panic log.
(github didn't let me upload .ips files so just change TXT to IPS)

Device: iPhone X (Global)
iOS Version: 16.7.5
[panic-full-2024-02-29-045625.000.txt](https://github.com/palera1n/jbinit/files/14451928/panic-full-2024-02-29-045625.000.txt)

**Comment by asdfugil** [comment]
please try to reproduce the issue with the commit 4d8ddc4b7c5f367f6dc260783d4d80242c2263da
