### ISSUE TITLE
I got an error when building use gmake on MacOS.

### ISSUE THREAD

**Issue by thanhlapvn** [palera1n/jbinit#14]
gmake -j$(sysctl -n hw.ncpu)
mkdir -p apple-include/{bsm,objc,os/internal,sys,firehose,CoreFoundation,FSEvents,IOSurface,IOKit/kext,libkern,kern,arm,{mach/,}machine,CommonCrypto,Security,CoreSymbolication,Kernel/{kern,IOKit,libkern},rpc,rpcsvc,xpc/private,ktrace,mach-o,dispatch}
gmake -C /Users/thanhlapvn/Desktop/b/jbinit/tools
cp -af /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include/{arpa,bsm,hfs,net,xpc,netinet,servers,timeconv.h,launch.h} apple-include
gmake[1]: Entering directory '/Users/thanhlapvn/Desktop/b/jbinit/tools'
mkdir -p "libdmg-hfsplus/build"
cd "libdmg-hfsplus/build" && cmake \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_C_COMPILER="cc" \
	-DCMAKE_C_FLAGS="" \
	-DZLIB_LIBRARY="-lz" -DZLIB_INCLUDE_DIR=" " \
	"/Users/thanhlapvn/Desktop/b/jbinit/tools/../tools/libdmg-hfsplus"
/bin/sh: line 1: cmake: command not found
gmake[1]: *** [Makefile:23: libdmg-hfsplus/build/Makefile] Error 127
gmake[1]: Leaving directory '/Users/thanhlapvn/Desktop/b/jbinit/tools'
cp: symlink: ../nameser.h: File exists
gmake: *** [Makefile:109: tools] Error 2
gmake: *** Waiting for unfinished jobs....
cp: symlink: ../bootstrap.h: File exists
cp: symlink: ../bootstrap.h: File exists
gmake: *** [Makefile:65: apple-include] Error 1

**Comment by severusvng** [comment]
git submodule update --init --recursive
