### ISSUE TITLE
bridgeos support

### ISSUE THREAD

**Issue by graphine27** [palera1n/jbinit#9]
Hi, I see some code around bridgeos, is it supported for the latest versions?

I can not connect via ssh (port 22 or 440 to it after all files uploaded

**Comment by alhaithammsar** [comment]
Hi, i have T2 jailbreak like checkra1n one that works on bridgeOS from 6.0 to 7.6+, also I have ssh ramdisk , lmk what you need these things for? Telegram @SDunlocks_91

**Comment by claration** [comment]
Closing issue, this was extremely past due to answering but we haven't gotten around to looking at every issue on the repository until now. BridgeOS support should be available with latest versions.
